version: '3'
services:
  lct-nginx:
    container_name: lct-nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default
    depends_on:
      - lct-front
      - lct-back
    logging:
        options:
          max-size: '50m'